/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Client_View.java
 *
 * Created on Jul 7, 2011, 11:17:55 PM
 */
package views;

/**
 *
 * @author warz07
 */
public class Client_View extends javax.swing.JFrame {

    /** Creates new form Client_View */
    public Client_View() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        clientID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        clientNameSearch = new javax.swing.JTextField();
        commercialClientSearch = new javax.swing.JCheckBox();
        businessClientSearch = new javax.swing.JCheckBox();
        searchClient = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        paymentMethodSearch = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        clientCitySearch = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        clientCountrySearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        clientFirstNameNew = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clientLastNameNew = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressClientNew = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clientCityNew = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clientStateNew = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        clientCountryNew = new javax.swing.JComboBox();
        usaCheckClient = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        homePhoneClient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        clientEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dobClient = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ssnClientNew = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        paymentMethodNew = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        businessRelationClient = new javax.swing.JTextArea();
        saveNewClient = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cancelClientAdd = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        clientCommercial = new javax.swing.JCheckBox();
        clientBusiness = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(891, 664));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(767, 563));

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/1310167614_emblem-people.png")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel21.setText("jLabel1");
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel22.setText("Search Clients");
        jLabel22.setName("jLabel22"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane2.setViewportView(jTable1);

        jLabel23.setText("Client ID");
        jLabel23.setName("jLabel23"); // NOI18N

        clientID.setName("clientID"); // NOI18N

        jLabel24.setText("Client Name");
        jLabel24.setName("jLabel24"); // NOI18N

        clientNameSearch.setName("clientNameSearch"); // NOI18N

        commercialClientSearch.setText("Commercial Clients");
        commercialClientSearch.setName("commercialClientSearch"); // NOI18N

        businessClientSearch.setText("Business Clients");
        businessClientSearch.setName("businessClientSearch"); // NOI18N

        searchClient.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/search_48.png")); // NOI18N
        searchClient.setName("searchClient"); // NOI18N

        jLabel25.setText("Payment Method");
        jLabel25.setName("jLabel25"); // NOI18N

        paymentMethodSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Master ", "Discover", "Paypal", "Check" }));
        paymentMethodSearch.setName("paymentMethodSearch"); // NOI18N

        jLabel26.setText("City");
        jLabel26.setName("jLabel26"); // NOI18N

        clientCitySearch.setName("clientCitySearch"); // NOI18N

        jLabel27.setText("Country");
        jLabel27.setName("jLabel27"); // NOI18N

        clientCountrySearch.setName("clientCountrySearch"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 925, Short.MAX_VALUE)
                .add(8, 8, 8))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel20)
                .add(7, 7, 7)
                .add(jLabel22)
                .addContainerGap(725, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel23)
                                .add(jLabel24))
                            .add(39, 39, 39)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(clientID)
                                .add(clientNameSearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .add(jLabel25)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(clientCitySearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .add(paymentMethodSearch, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(clientCountrySearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                    .add(jLabel26)
                    .add(jLabel27))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(180, 180, 180)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(commercialClientSearch)
                            .add(businessClientSearch))
                        .addContainerGap(305, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(searchClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(162, 162, 162))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 781, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(jLabel20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel21)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel23)
                                    .add(clientID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel24)
                                    .add(clientNameSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel25)
                                    .add(paymentMethodSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(commercialClientSearch)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(businessClientSearch)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel26)
                            .add(clientCitySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(clientCountrySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel27))
                        .add(18, 18, 18))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(searchClient)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );

        jTabbedPane1.addTab("Search Clients", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel16.setText("jLabel1");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Add New Client");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/1310167614_emblem-people.png")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Client Information");
        jLabel3.setName("jLabel3"); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel4.setText("First Name");
        jLabel4.setName("jLabel4"); // NOI18N

        clientFirstNameNew.setName("clientFirstNameNew"); // NOI18N

        jLabel5.setText("Last Name");
        jLabel5.setName("jLabel5"); // NOI18N

        clientLastNameNew.setName("clientLastNameNew"); // NOI18N

        jLabel6.setText("Physical Address");
        jLabel6.setName("jLabel6"); // NOI18N

        addressClientNew.setName("addressClientNew"); // NOI18N

        jLabel7.setText("City");
        jLabel7.setName("jLabel7"); // NOI18N

        clientCityNew.setName("clientCityNew"); // NOI18N

        jLabel8.setText("State");
        jLabel8.setName("jLabel8"); // NOI18N

        clientStateNew.setName("clientStateNew"); // NOI18N

        jLabel9.setText("Country");
        jLabel9.setName("jLabel9"); // NOI18N

        clientCountryNew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Austria", "Afghanistan\t", "Albania\t", "Australia\t", "Austria\t", "Azerbaijan\t", "Bahamas", "Bahrain\t", "Bangladesh\t", "Barbados\t", "Belarus", "Belgium\t", "Belize\t", "Benin\t", "Bermuda", "Bhutan\t", "Bolivia\t", "Bosnia and Herzegovina\t", "Botswana", " " }));
        clientCountryNew.setName("clientCountryNew"); // NOI18N

        usaCheckClient.setText("United States");
        usaCheckClient.setName("usaCheckClient"); // NOI18N

        jLabel10.setText("Home Phone");
        jLabel10.setName("jLabel10"); // NOI18N

        homePhoneClient.setName("homePhoneClient"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Business Information");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText("Email");
        jLabel12.setName("jLabel12"); // NOI18N

        clientEmail.setName("clientEmail"); // NOI18N

        jLabel13.setText("DOB");
        jLabel13.setName("jLabel13"); // NOI18N

        dobClient.setText("01/01/1989");
        dobClient.setName("dobClient"); // NOI18N

        jLabel14.setText("SSN");
        jLabel14.setName("jLabel14"); // NOI18N

        ssnClientNew.setName("ssnClientNew"); // NOI18N

        jLabel15.setText("Method of Payment");
        jLabel15.setName("jLabel15"); // NOI18N

        paymentMethodNew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Master ", "Discover", "Paypal", "Check" }));
        paymentMethodNew.setName("paymentMethodNew"); // NOI18N

        jLabel17.setText("Business Relation");
        jLabel17.setName("jLabel17"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        businessRelationClient.setColumns(20);
        businessRelationClient.setRows(5);
        businessRelationClient.setName("businessRelationClient"); // NOI18N
        jScrollPane1.setViewportView(businessRelationClient);

        saveNewClient.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/add_48.png")); // NOI18N
        saveNewClient.setBorderPainted(false);
        saveNewClient.setName("saveNewClient"); // NOI18N

        jLabel18.setText("Add Client");
        jLabel18.setName("jLabel18"); // NOI18N

        cancelClientAdd.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/cancel_48.png")); // NOI18N
        cancelClientAdd.setBorderPainted(false);
        cancelClientAdd.setName("cancelClientAdd"); // NOI18N

        jLabel19.setText("Cancel");
        jLabel19.setName("jLabel19"); // NOI18N

        clientCommercial.setText("Commercial Client");
        clientCommercial.setName("clientCommercial"); // NOI18N

        clientBusiness.setText("Business Client");
        clientBusiness.setName("clientBusiness"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(7, 7, 7)
                .add(jLabel1)
                .addContainerGap(577, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 925, Short.MAX_VALUE)
                .add(9, 9, 9))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addContainerGap(789, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel7)
                            .add(jLabel8)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(addressClientNew)
                                    .add(clientLastNameNew)
                                    .add(clientFirstNameNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(109, 109, 109)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel12)
                                    .add(jLabel13)
                                    .add(jLabel14))
                                .add(18, 18, 18)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(clientEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, ssnClientNew)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, dobClient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(clientCityNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(24, 24, 24)
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(clientCountryNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(usaCheckClient))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(clientStateNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(homePhoneClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(78, 78, 78)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(clientBusiness)
                                    .add(clientCommercial))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 253, Short.MAX_VALUE)))
                .addContainerGap())
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel11)
                .addContainerGap(770, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel15)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(paymentMethodNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(655, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel17)
                        .add(18, 18, 18)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(saveNewClient)
                            .add(jLabel18))
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(cancelClientAdd))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jLabel19))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 745, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel16)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(clientFirstNameNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel12)
                        .add(clientEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(clientLastNameNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(dobClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(addressClientNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(ssnClientNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(clientCityNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(clientCountryNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel9)
                        .add(usaCheckClient)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel8)
                        .add(clientStateNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(clientCommercial))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homePhoneClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(clientBusiness))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel11)
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(paymentMethodNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(cancelClientAdd)
                            .add(saveNewClient))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel18)
                            .add(jLabel19)))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Client", jPanel2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(50, 50, 50)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 818, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 654, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Client_View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressClientNew;
    private javax.swing.JCheckBox businessClientSearch;
    private javax.swing.JTextArea businessRelationClient;
    private javax.swing.JButton cancelClientAdd;
    private javax.swing.JCheckBox clientBusiness;
    private javax.swing.JTextField clientCityNew;
    private javax.swing.JTextField clientCitySearch;
    private javax.swing.JCheckBox clientCommercial;
    private javax.swing.JComboBox clientCountryNew;
    private javax.swing.JTextField clientCountrySearch;
    private javax.swing.JTextField clientEmail;
    private javax.swing.JTextField clientFirstNameNew;
    private javax.swing.JTextField clientID;
    private javax.swing.JTextField clientLastNameNew;
    private javax.swing.JTextField clientNameSearch;
    private javax.swing.JTextField clientStateNew;
    private javax.swing.JCheckBox commercialClientSearch;
    private javax.swing.JTextField dobClient;
    private javax.swing.JTextField homePhoneClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox paymentMethodNew;
    private javax.swing.JComboBox paymentMethodSearch;
    private javax.swing.JButton saveNewClient;
    private javax.swing.JButton searchClient;
    private javax.swing.JTextField ssnClientNew;
    private javax.swing.JCheckBox usaCheckClient;
    // End of variables declaration//GEN-END:variables
}
