/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Supplier_View.java
 *
 * Created on Jun 26, 2011, 6:05:03 PM
 */
package views;

import classes.Supplier;
import java.awt.event.ActionListener;
import models.Supplier_Model;

/**
 *
 * @author warz07
 */
public class Supplier_View extends javax.swing.JFrame {

    /*PRIVATE VARIABLES*/
    
   private Supplier supplier;
   private Supplier_Model supplierModel;
    
    /** Creates new form Supplier_View */
    public Supplier_View(Supplier_Model model) {
        
        
        initComponents();
        this.supplierModel = model;
        this.supplier = new Supplier();
        this.setTitle("Suppliers");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        SupplierTabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supplierLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplierID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        supplierGroup = new javax.swing.JTextField();
        supplierName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplierAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        supplierCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supplierState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        supplierProduct = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        supplierZip = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        localChecked = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        searchSupplier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cancelAddSupplier = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        supplierNameAdd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        supplierAddressAdd = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        SupplierZipCode = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        supplierCountry = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        supplierPhone = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        descriptionGoods = new javax.swing.JScrollPane();
        supplierGoods = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        supplierCityNew = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        SupplierTabPane.setName("Search"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        supplierLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        supplierLabel.setText("Search Supplier");
        supplierLabel.setName("supplierLabel"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Supplier ID");
        jLabel2.setName("jLabel2"); // NOI18N

        supplierID.setName("supplierID"); // NOI18N

        jLabel3.setText("Supplier Name");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Supplier Group");
        jLabel4.setName("jLabel4"); // NOI18N

        supplierGroup.setName("supplierGroup"); // NOI18N

        supplierName.setName("supplierName"); // NOI18N

        jLabel6.setText("Address");
        jLabel6.setName("jLabel6"); // NOI18N

        supplierAddress.setName("supplierAddress"); // NOI18N

        jLabel7.setText("City");
        jLabel7.setName("jLabel7"); // NOI18N

        supplierCity.setName("supplierCity"); // NOI18N

        jLabel8.setText("State");
        jLabel8.setName("jLabel8"); // NOI18N

        supplierState.setName("supplierState"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel9.setText("Example (MN, ND, CA..)");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Supplier Prod.");
        jLabel10.setName("jLabel10"); // NOI18N

        supplierProduct.setName("supplierProduct"); // NOI18N

        jLabel11.setText("Zip Code");
        jLabel11.setName("jLabel11"); // NOI18N

        supplierZip.setName("supplierZip"); // NOI18N

        jLabel12.setText("Area");
        jLabel12.setName("jLabel12"); // NOI18N

        localChecked.setText("Local");
        localChecked.setName("localChecked"); // NOI18N

        jCheckBox2.setText("International");
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        cancelButton.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/cancel_48.png")); // NOI18N
        cancelButton.setBorderPainted(false);
        cancelButton.setName("cancelButton"); // NOI18N

        jLabel14.setText("Cancel");
        jLabel14.setName("jLabel14"); // NOI18N

        searchButton.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/search_48.png")); // NOI18N
        searchButton.setBorderPainted(false);
        searchButton.setName("searchButton"); // NOI18N

        jLabel13.setText("Search");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/1310172118_agency.png")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N

        searchSupplier.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/search_48.png")); // NOI18N
        searchSupplier.setName("searchSupplier"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jLabel10)
                                .add(18, 18, 18)
                                .add(supplierProduct))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(supplierGroup))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel2))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(supplierName)
                                    .add(supplierID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(56, 56, 56)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jLabel7)
                                    .add(jLabel8))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(supplierCity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(supplierAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(supplierState, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(jLabel9))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel11)
                                    .add(jLabel12))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(localChecked)
                                        .add(18, 18, 18)
                                        .add(jCheckBox2))
                                    .add(supplierZip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(44, 44, 44)
                        .add(searchSupplier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 202, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(searchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel13)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel14)
                                    .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(69, 69, 69))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel29)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(supplierLabel))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 763, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
                .add(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel29)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(supplierLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabel2)
                                            .add(supplierID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabel3)
                                            .add(supplierName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(20, 20, 20)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabel4)
                                            .add(supplierGroup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(18, 18, 18)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabel10)
                                            .add(supplierProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(searchButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel13)
                                        .add(18, 18, 18)
                                        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel14))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6)
                                    .add(supplierAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel7)
                                    .add(supplierCity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel8)
                                    .add(supplierState, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel9))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel11)
                                    .add(supplierZip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel12)
                                    .add(localChecked)
                                    .add(jCheckBox2))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, 22, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(searchSupplier)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 326, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16))
        );

        SupplierTabPane.addTab("Search Supplier", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel15.setText("jLabel1");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setText("Add New Supplier");
        jLabel16.setName("jLabel16"); // NOI18N

        addButton.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/add_48.png")); // NOI18N
        addButton.setBorderPainted(false);
        addButton.setName("addButton"); // NOI18N

        jLabel17.setText("Add Supplier");
        jLabel17.setName("jLabel17"); // NOI18N

        cancelAddSupplier.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/cancel_48.png")); // NOI18N
        cancelAddSupplier.setBorderPainted(false);
        cancelAddSupplier.setName("cancelAddSupplier"); // NOI18N

        jLabel18.setText("Cancel");
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setText("Refresh");
        jLabel19.setName("jLabel19"); // NOI18N

        refreshButton.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/function_icon_set/refresh_48.png")); // NOI18N
        refreshButton.setBorderPainted(false);
        refreshButton.setName("refreshButton"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("About the Company");
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setText("Supplier Full Name");
        jLabel21.setName("jLabel21"); // NOI18N

        supplierNameAdd.setName("supplierNameAdd"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel22.setText("Supplier Address");
        jLabel22.setName("jLabel22"); // NOI18N

        supplierAddressAdd.setName("supplierAddressAdd"); // NOI18N

        jLabel23.setText("Zip Code");
        jLabel23.setName("jLabel23"); // NOI18N

        SupplierZipCode.setName("SupplierZipCode"); // NOI18N

        jLabel24.setText("Country");
        jLabel24.setName("jLabel24"); // NOI18N

        supplierCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guatemala", "Brazil", "Germany", "Italy", "France", "Portugal", "Jamaica", " " }));
        supplierCountry.setName("supplierCountry"); // NOI18N

        jCheckBox1.setText("United States");
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jLabel25.setText("Phone Number");
        jLabel25.setName("jLabel25"); // NOI18N

        supplierPhone.setName("supplierPhone"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel26.setText("Format (xxx-xxx-xxxx)");
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText("Nature of Goods or Services provided by Supplier ");
        jLabel27.setName("jLabel27"); // NOI18N

        descriptionGoods.setName("descriptionGoods"); // NOI18N

        supplierGoods.setColumns(20);
        supplierGoods.setRows(5);
        supplierGoods.setName("supplierGoods"); // NOI18N
        descriptionGoods.setViewportView(supplierGoods);

        jLabel28.setText("City");
        jLabel28.setName("jLabel28"); // NOI18N

        supplierCityNew.setName("supplierCityNew"); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/1310172118_agency.png")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 964, Short.MAX_VALUE)
                .add(6, 6, 6))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel17)
                    .add(addButton))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(cancelAddSupplier)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(refreshButton))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jLabel18)
                        .add(26, 26, 26)
                        .add(jLabel19)))
                .add(198, 198, 198))
            .add(jPanel2Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel16)
                .addContainerGap(534, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel27)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionGoods)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel25)
                                .add(jLabel24))
                            .add(39, 39, 39)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(supplierPhone)
                                .add(supplierCountry, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel26)
                                .add(jCheckBox1))
                            .add(4, 4, 4)))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 849, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel21)
                            .add(jLabel22)
                            .add(jLabel28)
                            .add(jLabel23))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SupplierZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(supplierCityNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(supplierAddressAdd)
                                .add(supplierNameAdd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel16)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel15)
                .add(18, 18, 18)
                .add(jLabel20)
                .add(4, 4, 4)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel21)
                    .add(supplierNameAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(supplierAddressAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28)
                    .add(supplierCityNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SupplierZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel23))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel25)
                                    .add(supplierPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(41, 41, 41)
                                .add(jLabel26)))
                        .add(18, 18, 18)
                        .add(jLabel27)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(descriptionGoods, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(supplierCountry, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jCheckBox1))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jLabel24)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(addButton)
                    .add(cancelAddSupplier)
                    .add(refreshButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(jLabel18)
                    .add(jLabel19))
                .add(32, 32, 32))
        );

        SupplierTabPane.addTab("Add Supplier", jPanel2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(SupplierTabPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 811, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(SupplierTabPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 698, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Supplier_View().setVisible(true);
            }
        });
    }
    */
    
    /**
     * Function is designed to create a supplier object and set its properties using 
     * the correct supplier methods.
     */
    
    public void setSupplier(){
    
        String SupplierName = this.supplierName.getText();
        int SupplierID = Integer.parseInt(this.supplierID.getText());
        String SupplierPhone = this.supplierPhone.getText();
        String SupplierZip = this.SupplierZipCode.getText();
        String SupplierCity = this.supplierCityNew.getText();
        String SupplierAddress = this.supplierAddressAdd.getText();
        String SupplierGoods = this.supplierGoods.getText();
        String SupplierCountry = (String)this.supplierCountry.getSelectedItem();
        
        this.supplier = new Supplier(SupplierName, SupplierCountry, SupplierPhone, SupplierAddress, SupplierCity, SupplierZip, SupplierGoods);
    System.out.println("supplier info " + this.supplier.formatTostring());
    }
    
   public Supplier getSupplier(){
   
   
   return this.supplier;
   
   } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane SupplierTabPane;
    private javax.swing.JTextField SupplierZipCode;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelAddSupplier;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane descriptionGoods;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox localChecked;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchSupplier;
    private javax.swing.JTextField supplierAddress;
    private javax.swing.JTextField supplierAddressAdd;
    private javax.swing.JTextField supplierCity;
    private javax.swing.JTextField supplierCityNew;
    private javax.swing.JComboBox supplierCountry;
    private javax.swing.JTextArea supplierGoods;
    private javax.swing.JTextField supplierGroup;
    private javax.swing.JTextField supplierID;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierNameAdd;
    private javax.swing.JTextField supplierPhone;
    private javax.swing.JTextField supplierProduct;
    private javax.swing.JTextField supplierState;
    private javax.swing.JTextField supplierZip;
    // End of variables declaration//GEN-END:variables

    public void addSaveListener(ActionListener saveListener) {
        addButton.addActionListener(saveListener);
    }
    
    public void addCloseListener(ActionListener closeListener){
    
    cancelButton.addActionListener(closeListener);
    cancelAddSupplier.addActionListener(closeListener);
    }
    
    /*Local Variables being set declerations*/
    public void close() {
        this.dispose();
    }
}
